# Generated by Django 4.0.1 on 2022-02-01 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fullname', models.CharField(blank=True, max_length=512, null=True)),
                ('first_name', models.CharField(blank=True, max_length=512, null=True)),
                ('last_name', models.CharField(blank=True, max_length=512, null=True)),
                ('locale', models.CharField(default='en', max_length=5)),
                ('avatar_url', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
